spring:
  profiles:
    active: '@spring.profiles.active@'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
server:
  port: 9000
debug: true
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_ampos_restaurant?useSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password:
---
spring:
  profiles: document
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo_ampos_restaurant;mode=mysql
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
output:
  dir:
    html: '@output.dir.html@'
---
spring:
  profiles: docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      initialization-fail-timeout: 0